[auth]
redirect_uri = "http://localhost:8502/syngular-solutions-app-web/oauth2callback"
cookie_secret = "xxx"
client_id = "677282368674-rc180gaqp4mu0hfjot9d1pibs02728t8.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
